from django.db import models

class ProcessedForecastData(models.Model):
    id = models.AutoField(primary_key=True)
    temp = models.FloatField(null=True, blank=True)
    feelslike = models.FloatField(null=True, blank=True)
    dew = models.FloatField(null=True, blank=True)
    humidity = models.FloatField(null=True, blank=True)
    windspeed = models.FloatField(null=True, blank=True)
    winddir = models.FloatField(null=True, blank=True)
    sealevelpressure = models.FloatField(null=True, blank=True)
    cloudcover = models.FloatField(null=True, blank=True)
    visibility = models.FloatField(null=True, blank=True)
    uvindex = models.IntegerField(null=True, blank=True)
    conditions = models.IntegerField(null=True, blank=True)
    Time_Zone = models.CharField(max_length=255, null=True, blank=True)
    Load = models.FloatField(null=True, blank=True)
    year = models.IntegerField(null=True, blank=True)
    month = models.IntegerField(null=True, blank=True)
    day = models.IntegerField(null=True, blank=True)
    hour = models.IntegerField(null=True, blank=True)
    day_of_week = models.IntegerField(null=True, blank=True)
    Load_avg_prev_day = models.FloatField(null=True, blank=True)
    temp_avg_prev_day = models.FloatField(null=True, blank=True)