# Generated by Django 5.0.1 on 2024-01-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedForecastData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('temp', models.FloatField(blank=True, null=True)),
                ('feelslike', models.FloatField(blank=True, null=True)),
                ('dew', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('windspeed', models.FloatField(blank=True, null=True)),
                ('winddir', models.FloatField(blank=True, null=True)),
                ('sealevelpressure', models.FloatField(blank=True, null=True)),
                ('cloudcover', models.FloatField(blank=True, null=True)),
                ('visibility', models.FloatField(blank=True, null=True)),
                ('uvindex', models.IntegerField(blank=True, null=True)),
                ('conditions', models.IntegerField(blank=True, null=True)),
                ('Time_Zone', models.CharField(blank=True, max_length=255, null=True)),
                ('Load', models.FloatField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('day', models.IntegerField(blank=True, null=True)),
                ('hour', models.IntegerField(blank=True, null=True)),
                ('day_of_week', models.IntegerField(blank=True, null=True)),
                ('Load_avg_prev_day', models.FloatField(blank=True, null=True)),
                ('temp_avg_prev_day', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawForecastLoadData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('TimeStamp', models.CharField(blank=True, max_length=255, null=True)),
                ('TimeZone', models.CharField(blank=True, max_length=255, null=True)),
                ('Name', models.CharField(blank=True, max_length=255, null=True)),
                ('PTID', models.BigIntegerField(blank=True, null=True)),
                ('Load', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawForecastWeatherData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('temp', models.FloatField(blank=True, null=True)),
                ('feelslike', models.FloatField(blank=True, null=True)),
                ('dew', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('precip', models.FloatField(blank=True, null=True)),
                ('precipprob', models.FloatField(blank=True, null=True)),
                ('preciptype', models.FloatField(blank=True, null=True)),
                ('snow', models.FloatField(blank=True, null=True)),
                ('snowdepth', models.FloatField(blank=True, null=True)),
                ('windgust', models.FloatField(blank=True, null=True)),
                ('windspeed', models.FloatField(blank=True, null=True)),
                ('winddir', models.IntegerField(blank=True, null=True)),
                ('sealevelpressure', models.FloatField(blank=True, null=True)),
                ('cloudcover', models.FloatField(blank=True, null=True)),
                ('visibility', models.FloatField(blank=True, null=True)),
                ('solarradiation', models.IntegerField(blank=True, null=True)),
                ('solarenergy', models.FloatField(blank=True, null=True)),
                ('uvindex', models.IntegerField(blank=True, null=True)),
                ('severerisk', models.BooleanField(blank=True, null=True)),
                ('conditions', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
